flowchart TB


subgraph Azure_Cloud_Platform_Project
    subgraph Global_Cloud_Load_Balancer
    Forwarding_Rule
    Target_HTTP_Proxy
    URL_Map
    Backend_Service
    Health_Check
        subgraph Azure_WAF
            IP_Allow/Deny
            Geo
            WAF
            Custom_Rules_L3-L7
        end 
    end 
    subgraph GCP_Account
        subgraph Project
            subgraph GCP_Service_Account
              117681674265526344599
              JSON_Key_Stored_In_TC_Sensitive_Environment_Variable
              
              end   
         end       
    end
subgraph VCP
    subgraph GCP_Zone_US_Central_1-a
     subgraph Sub1_10.0.0.0.0/24
        Redhat_Compute_Intance o--o interface1
        Redhat_Compute_Intance o--o Storage_20GB
        end
     subgraph Sub2_10.0.10.0/24
        sub2
        end
        subgraph Sub3_10.0.20.0.0/24
        Redhat_Compute_Intance2_With_Apache o--o interface3
        Redhat_Compute_Intance2_With_Apache o--o Storage_20-GB
        end
        subgraph Sub4_10.0.30.0/24
        sub4
        end
        
    end
end
end
Web_Browser_Client o--o Global_Cloud_Load_Balancer
GitHub_Repo o--o Terraform_Cloud_Account
Terraform_Cloud_Account o--o GCP_Account
Global_Cloud_Load_Balancer o--o Sub3_10.0.20.0.0/24




subgraph Application
    subgraph Service_Project
        subgraph Resources
        end
    end
end

